name: pet_project
description: "A new Flutter project."
publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: ^3.5.1
#  sdk: ^3.5.2

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  google_fonts: ^6.2.1
  go_router: ^14.2.7
  flutter_svg: ^2.0.10+1
  device_preview: ^1.2.0
  image_picker: ^1.1.2
  share_plus: ^10.0.2
  avatar_glow: ^3.0.1
  # video_player: ^2.9.2
  permission_handler: ^11.3.1
  cached_network_image: ^3.4.1
  flutter_staggered_grid_view: ^0.7.0
  shimmer: ^3.0.0
  smooth_page_indicator: ^1.2.0+3
  country_picker: ^2.0.26
  flutter_gallery_3d: ^1.1.1
  shared_preferences: ^2.3.2
  flutter_rating_stars: ^1.1.0
  avatar_stack: ^1.2.0
  provider: ^6.1.2
  carousel_custom_slider: ^0.0.7+3
  material_design_icons_flutter: ^7.0.7296
  easy_localization: ^3.0.7
  flutter_quill: 
  link_text: 
  http:
  flutter_chat_reactions: ^0.1.0
  emoji_picker_flutter: ^3.1.0
  flutter_reaction_button: ^3.0.0+3
  persistent_bottom_nav_bar: 
  photo_view: 
  loader_overlay: ^4.0.3
  firebase_core: ^3.6.0
  firebase_messaging: ^15.1.3
  timeago: ^3.7.0
  story_view: ^0.16.5
  googleapis: 
  googleapis_auth: ^1.0.0
  flutter_local_notifications: ^18.0.1
  


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.14.1

  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/icons/
    - assets/translations/

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/splashdog.png"
  min_sdk_android: 23
  adaptive_icon_background: "#FFFFFFFF"
  adaptive_icon_foreground: "assets/images/splashdog.png"
